FROM debian:bookworm-slim

# ⋆˙⟡ icecast2 from debian
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y --no-install-recommends icecast2 \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /var/log/icecast2 \
    && chown nobody:nogroup /var/log/icecast2

COPY icecast.xml /etc/icecast2/icecast.xml

EXPOSE 8000

CMD ["icecast2", "-c", "/etc/icecast2/icecast.xml"]
